### ISSUE TITLE
Annotation module - Error: local class incompatible: stream classdesc serialVersionUID

### ISSUE THREAD

**Issue by Paula-V-IPT** [cougarlj/COMPSRA#12]
Dear COMPSRA team,
I am following your tutorial and the modules Quality Control and Alignment were successful both for an example datafile from yours and for an actual sample.
Now I am having trouble with the **Annotation** Module:
I copy your code:
`java -jar COMPSRA.jar -ref hg38 -ann -ac 1,2,3,4,5,6 -in ./example_out/sample01/sample01_17to50_FitRead_STAR_Aligned.out.bam -out ./example_out/sample01/sample01_17to50_FitRead_STAR_Aligned`
and I get the following:
`+++++++++++++++++++++++++++++++
+            COMPSRA          +
+     (V1.0.2 2020-07-03)     +
+  rejia@channing.harvard.edu +
+++++++++++++++++++++++++++++++

Working Directory: /home/ipt/Documents/COMPSRA
Bundle Directory: /home/ipt/Documents/COMPSRA/bundle_v1
Configuration Directory: /home/ipt/Documents/COMPSRA/bundle_v1/configuration
Plug Directory: /home/ipt/Documents/COMPSRA/bundle_v1/plug
N_CPU: 48

Configuration Info: The endogenous database configuration has been set!
Configuration Info: 37 databases are set!
13:29:09.683 [main] INFO  edu.harvard.channing.compass.core.Configuration - The Configuration was completed!

The hg38 reference genome was set.
QC module will not be performed.
Alignment module will not be performed.
Microbe module will not be performed.
Function module will not be performed.

+++++++++++++++++++++++++++++++
+   Module  --->  Annotation  +
+++++++++++++++++++++++++++++++

DEBUG	2021-01-27 13:29:09	BlockCompressedOutputStream	Using deflater: Deflater
13:29:09.729 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - edu.harvard.channing.compass.entity.DBTree; local class incompatible: stream classdesc serialVersionUID = 556476181312992002, local class serialVersionUID = 1386352989058994328
13:29:09.730 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - Fail to find the prebuilt database obj file!
13:29:09.730 [pool-2-thread-1] WARN  edu.harvard.channing.compass.db.DB_miRBase - The prebuilt database file /home/ipt/Documents/COMPSRA/bundle_v1/prebuilt_db/miRBase_hg38.obj doesn't exist!
13:29:09.730 [pool-2-thread-1] INFO  edu.harvard.channing.compass.db.DB_miRBase - Try to build the database from local files /home/ipt/Documents/COMPSRA/bundle_v1/db/miRBase/miRBase_hg38.gff3 !
13:29:09.730 [pool-2-thread-1] INFO  edu.harvard.channing.compass.core.Factory - Read File Error: Fail to read file: miRBase_v21
13:29:09.730 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - null
13:29:09.730 [pool-2-thread-1] INFO  edu.harvard.channing.compass.utility.ReadFile - Read File Error: Fail to read file: /home/ipt/Documents/COMPSRA/bundle_v1/db/miRBase/miRBase_hg38.gff3.
13:29:09.730 [pool-2-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - null
java.lang.NullPointerException
	at edu.harvard.channing.compass.utility.ReadFile.readGFF3(ReadFile.java:384)
	at edu.harvard.channing.compass.db.DB_miRBase.getForest(DB_miRBase.java:102)
	at edu.harvard.channing.compass.core.ann.IPTR_miRNA.buildForest(IPTR_miRNA.java:51)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.Annotate(SAMAnnotator.java:79)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.call(SAMAnnotator.java:160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
13:29:09.731 [main] ERROR edu.harvard.channing.compass.core.ann.Annotation - java.lang.NullPointerException
13:29:09.731 [main] INFO  edu.harvard.channing.compass.core.Produce - Error: Annotation module fails!

+++++++++++++++++++++++++++++++++++++++
+  The COMPSRA pipeline was finished! +
+           Welcome to use!           +
+++++++++++++++++++++++++++++++++++++++
`

I do not think the problem are the prebuilt databases (The prebuilt database file ....obj doesn't exist!) because the objects do exist and are in the mentioned directory.
I downloaded them through the commands and also through the html links.

Could you help to get this step running?

I am not a java user, I only followed your tutorial for the specific purpose of small RNA-Seq, and when googling for answers I ended up "loster".

**Comment by cougarlj** [comment]
Dear Paula-V-IPT,

The reason is that the COMPSRA version is not consist with the pre-built database version. Because our server is not robust, please download COMPSRA (https://github.com/cougarlj/COMPSRA/blob/master/COMPSRA_V1.0.3.zip) and pre-built database (https://github.com/cougarlj/COMPSRA/tree/master/bundle_v1/prebuilt_db) directly from GitHub. 

Best Wishes,
  Jiang Li

**Comment by Paula-V-IPT** [comment]
Dear Jiang Li,
thank you for your quick answer! I will try that.
Best,
Paula

**Comment by YoonheeJ** [comment]
Hi Jiang Li,

I can't find the piRBase_mm10.obj in (https://github.com/cougarlj/COMPSRA/tree/master/bundle_v1/prebuilt_db).
Could you please upload it? I keep having error of annotation to piRNA.
Thank you, 
YH

**Comment by cougarlj** [comment]
Do you mean
https://github.com/cougarlj/COMPSRA/blob/master/bundle_v1/prebuilt_db/piRBase_hg38.obj
?

**Comment by YoonheeJ** [comment]
I mean mm10.

**Comment by cougarlj** [comment]
Dear YoonheeJ,

There are huge number of items of mouse piRNAs in piRBase. I'm not sure the reason and they don't respond to me. If you could, you can download from https://regepi.bwh.harvard.edu/circurna/bundle_v1/prebuilt_db/piRBase_mm10.obj . 

Best Wishes,
  Jiang

**Comment by YoonheeJ** [comment]
Hi Jiang,

Thanks for the information,
I tried to download the piRBase_mm10.obj from that link, but it failed (only failed with mm9 and mm10). Is there any other place  I could download?
Thanks again.
YH

**Comment by cougarlj** [comment]
Hi, YoonheeJ,

The file is too large to upload to GitHub. I suggest that you could use piRBank_mm10.obj. 

Best Wishes,
  Jiang Li

**Comment by YoonheeJ** [comment]
OK, Thank you!!

Best,
YH

**Comment by ANDdna1991** [comment]
Hello, 

I'm just starting in the smallRNA seq world and I would like to use COMPSRA.  I followed the manual but I'm finding the same issue. I'm just using the example datafile. The Quality Control and Alignment were fine, however, when I try to run the Annotation modules it crashes. I have already downloaded the prebuild databases from here but the problem persist. 

I don't know which exactly is the problem, it reports miRBase_hg38.obj doesn't exist! but it exists:

prebuilt_db]$ ls | grep "miRBase_hg38.obj"
miRBase_hg38.obj

I let the complete output. Basically, I'm just submitting the codes from the manual.

+++++++++++++++++++++++++++++++
+            COMPSRA          +
+     (V1.0.2 2020-07-03)     +
+  rejia@channing.harvard.edu +
+++++++++++++++++++++++++++++++

Configuration Info: The endogenous database configuration has been set!
Configuration Info: 37 databases are set!
18:46:42.310 [main] INFO  edu.harvard.channing.compass.core.Configuration - The Configuration was completed!

The hg38 reference genome was set.
QC module will not be performed.
Alignment module will not be performed.
Microbe module will not be performed.
Function module will not be performed.

+++++++++++++++++++++++++++++++
+   Module  --->  Annotation  +
+++++++++++++++++++++++++++++++

18:46:42.377 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - Not in GZIP format
18:46:42.377 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - Fail to find the prebuilt database obj file!
18:46:42.377 [pool-2-thread-1] WARN  edu.harvard.channing.compass.db.DB_miRBase - The prebuilt database file /rds/project/rds-XUr6B1Jhndg/ah2192_backup/projects/small_rna_seq/COMPSRA/bundle_v1/prebuilt_db/miRBase_hg38.obj doesn't exist!
18:46:42.378 [pool-2-thread-1] INFO  edu.harvard.channing.compass.db.DB_miRBase - Try to build the database from local files /rds/project/rds-XUr6B1Jhndg/ah2192_backup/projects/small_rna_seq/COMPSRA/bundle_v1/db/miRBase/miRBase_hg38.gff3 !
18:46:42.378 [pool-2-thread-1] INFO  edu.harvard.channing.compass.core.Factory - Read File Error: Fail to read file: miRBase_v21
18:46:42.378 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - null
18:46:42.379 [pool-2-thread-1] INFO  edu.harvard.channing.compass.utility.ReadFile - Read File Error: Fail to read file: /rds/project/rds-XUr6B1Jhndg/ah2192_backup/projects/small_rna_seq/COMPSRA/bundle_v1/db/miRBase/miRBase_hg38.gff3.
18:46:42.380 [pool-2-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - null
18:46:42.381 [main] ERROR edu.harvard.channing.compass.core.ann.Annotation - java.lang.NullPointerException
18:46:42.381 [main] INFO  edu.harvard.channing.compass.core.Produce - Error: Annotation module fails!


+++++++++++++++++++++++++++++++++++++++
+  The COMPSRA pipeline was finished! +
+           Welcome to use!           +
+++++++++++++++++++++++++++++++++++++++

Any input is more than welcome!
Thanks,
And

**Comment by cougarlj** [comment]
Dear ANDdna1991, 

According to the error message, it seems that COMPSRA couldn't download the pre-built database by itself.  Because our server is not robust, please download COMPSRA (https://github.com/cougarlj/COMPSRA/blob/master/COMPSRA_V1.0.3.zip) and pre-built database (https://github.com/cougarlj/COMPSRA/tree/master/bundle_v1/prebuilt_db) directly from GitHub. After that, please put these obj files in .../bundle_v1/prebuilt_db/ . 

Best Wishes,
Jiang Li

**Comment by ANDdna1991** [comment]
Dear Jiang Li,

I've uninstalled and reinstalled COMPSRA as you suggest directly from GitHub. I also have downloaded the pre-built database directly from GitHub.

!# here you can see the files are in prebuilt_db folder.

prebuilt_db]$ ls
circBase_hg38.obj gencode_snoRNA_hg38.obj  GtRNAdb_hg38.obj  piRBase_hg38.obj    piRNACluster_hg38.obj gencode_lncRNA_hg38.obj  gencode_snRNA_hg38.obj   miRBase_hg38.obj  piRNABank_hg38.obj

However, the problem persists, the error is the same. The annotation module fails to find the database obj files. Could you give me some clue to solve this? 

16:07:55.922 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - Not in GZIP format
16:07:55.922 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - Fail to find the prebuilt database obj file!
16:07:55.922 [pool-2-thread-1] WARN  edu.harvard.channing.compass.db.DB_miRBase - The prebuilt database file /rds/project/rds-XUr6B1Jhndg/ah2192_backup/projects/small_rna_seq/COMPSRA/bundle_v1/prebuilt_db/miRBase_hg38.obj doesn't exist!
16:07:55.922 [pool-2-thread-1] INFO  edu.harvard.channing.compass.db.DB_miRBase - Try to build the database from local files /rds/project/rds-XUr6B1Jhndg/ah2192_backup/projects/small_rna_seq/COMPSRA/bundle_v1/db/miRBase/miRBase_hg38.gff3 !
16:07:55.923 [pool-2-thread-1] INFO  edu.harvard.channing.compass.core.Factory - Read File Error: Fail to read file: miRBase_v21
16:07:55.923 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - null
16:07:55.924 [pool-2-thread-1] INFO  edu.harvard.channing.compass.utility.ReadFile - Read File Error: Fail to read file: /rds/project/rds-XUr6B1Jhndg/ah2192_backup/projects/small_rna_seq/COMPSRA/bundle_v1/db/miRBase/miRBase_hg38.gff3.
16:07:55.924 [pool-2-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - null
16:07:55.925 [main] ERROR edu.harvard.channing.compass.core.ann.Annotation - java.lang.NullPointerException
16:07:55.925 [main] INFO  edu.harvard.channing.compass.core.Produce - Error: Annotation module fails!

kind Regards, 
Andres

**Comment by cougarlj** [comment]
Dear ANDdna1991,

Please also make sure the directory prebuilt_db is located in bundle_v1.

Best regards,
  Jiang
