### ISSUE TITLE
Not in GZIP format error in Annotation module

### ISSUE THREAD

**Issue by Ben7124** [cougarlj/COMPSRA#14]
Hello,

I successfully pass the QC and alignment steps, but I get the below errors in the annotation step. Can you please help me?

+++++++++++++++++++++++++++++++
+   Module  --->  Annotation  +
+++++++++++++++++++++++++++++++

DEBUG	2021-04-09 01:19:33	BlockCompressedOutputStream	Using deflater: Deflater
01:19:33.800 [pool-4-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - Not in GZIP format
01:19:33.800 [pool-4-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - Fail to find the prebuilt database obj file!
01:19:33.801 [pool-4-thread-1] WARN  edu.harvard.channing.compass.db.DB_miRBase - The prebuilt database file /data/COMPSRA/bundle_v1/prebuilt_db/miRBase_hg38.obj doesn't exist!
01:19:33.801 [pool-4-thread-1] INFO  edu.harvard.channing.compass.db.DB_miRBase - Try to build the database from local files /data/COMPSRA/bundle_v1/db/miRBase/miRBase_hg38.gff3 !
01:19:33.801 [pool-4-thread-1] INFO  edu.harvard.channing.compass.core.Factory - Read File Error: Fail to read file: miRBase_v21
01:19:33.801 [pool-4-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - null
01:19:33.802 [pool-4-thread-1] INFO  edu.harvard.channing.compass.utility.ReadFile - Read File Error: Fail to read file: /data/COMPSRA/bundle_v1/db/miRBase/miRBase_hg38.gff3.
01:19:33.802 [pool-4-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - null
java.lang.NullPointerException
	at edu.harvard.channing.compass.utility.ReadFile.readGFF3(ReadFile.java:384)
	at edu.harvard.channing.compass.db.DB_miRBase.getForest(DB_miRBase.java:102)
	at edu.harvard.channing.compass.core.ann.IPTR_miRNA.buildForest(IPTR_miRNA.java:51)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.Annotate(SAMAnnotator.java:79)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.call(SAMAnnotator.java:160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
01:19:33.804 [main] ERROR edu.harvard.channing.compass.core.ann.Annotation - java.lang.NullPointerException
01:19:33.804 [main] INFO  edu.harvard.channing.compass.core.Produce - Error: Annotation module fails!

**Comment by cougarlj** [comment]
Please download the pre-built databases before you run the annotation
module.
