### ISSUE TITLE
Error opening file and FileNotFound

### ISSUE THREAD

**Issue by DAE-113** [cougarlj/COMPSRA#16]
Hello,

I am trying to use the annotation module on its own and getting back 2 errors that I am unable to troubleshoot on my own.

My command is as follows with STARsamples leading to a text file and samples out being the output directory:
java -jar $EBROOTCOMPSRA/COMPSRA.jar -ref hg38 -ann -ac 1,2,3,4,5,6 -inf "$STARsamples" -out "$samplesout"

There are 6 samples in the text file and all of them come back with the same two errors. The output folder has the following txt files made but nothing else: COMPSRA_DEG_0_circRNA.txt  COMPSRA_DEG_0_miRNA.txt  COMPSRA_DEG_0_piRNA.txt  COMPSRA_DEG_0_snoRNA.txt  COMPSRA_DEG_0_snRNA.txt	COMPSRA_DEG_0_tRNA.txt 

I get back the following errors:

+++++++++++++++++++++++++++++++++++++++
+  The COMPSRA pipeline was finished! +
+           Welcome to use!           +
+++++++++++++++++++++++++++++++++++++++

Thu Apr 15 16:13:28 EDT 2021
16:13:28.990 [pool-2-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - Error opening file: /gpfs/ysm/project/neugebauer/da498/20210303coilRNAseq/2_pipeline/8_COMPSRA/C2_Aligned/C2_Aligned_UnMapped.bam
htsjdk.samtools.util.RuntimeIOException: Error opening file: /gpfs/ysm/project/neugebauer/da498/20210303coilRNAseq/2_pipeline/8_COMPSRA/C2_Aligned/C2_Aligned_UnMapped.bam
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:246)
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:215)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.Annotate(SAMAnnotator.java:60)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.call(SAMAnnotator.java:160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
16:13:29.061 [pool-2-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - Error opening file: /gpfs/ysm/project/neugebauer/da498/20210303coilRNAseq/2_pipeline/8_COMPSRA/C3_Aligned/C3_Aligned_UnMapped.bam
htsjdk.samtools.util.RuntimeIOException: Error opening file: /gpfs/ysm/project/neugebauer/da498/20210303coilRNAseq/2_pipeline/8_COMPSRA/C3_Aligned/C3_Aligned_UnMapped.bam
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:246)
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:215)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.Annotate(SAMAnnotator.java:60)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.call(SAMAnnotator.java:160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
16:13:29.116 [pool-2-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - Error opening file: /gpfs/ysm/project/neugebauer/da498/20210303coilRNAseq/2_pipeline/8_COMPSRA/NT1_Aligned/NT1_Aligned_UnMapped.bam
htsjdk.samtools.util.RuntimeIOException: Error opening file: /gpfs/ysm/project/neugebauer/da498/20210303coilRNAseq/2_pipeline/8_COMPSRA/NT1_Aligned/NT1_Aligned_UnMapped.bam
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:246)
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:215)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.Annotate(SAMAnnotator.java:60)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.call(SAMAnnotator.java:160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
16:13:29.158 [pool-2-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - Error opening file: /gpfs/ysm/project/neugebauer/da498/20210303coilRNAseq/2_pipeline/8_COMPSRA/NT2_Aligned/NT2_Aligned_UnMapped.bam
htsjdk.samtools.util.RuntimeIOException: Error opening file: /gpfs/ysm/project/neugebauer/da498/20210303coilRNAseq/2_pipeline/8_COMPSRA/NT2_Aligned/NT2_Aligned_UnMapped.bam
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:246)
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:215)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.Annotate(SAMAnnotator.java:60)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.call(SAMAnnotator.java:160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
16:13:29.203 [pool-2-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - Error opening file: /gpfs/ysm/project/neugebauer/da498/20210303coilRNAseq/2_pipeline/8_COMPSRA/NT3_Aligned/NT3_Aligned_UnMapped.bam
htsjdk.samtools.util.RuntimeIOException: Error opening file: /gpfs/ysm/project/neugebauer/da498/20210303coilRNAseq/2_pipeline/8_COMPSRA/NT3_Aligned/NT3_Aligned_UnMapped.bam
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:246)
	at htsjdk.samtools.SAMFileWriterFactory.makeBAMWriter(SAMFileWriterFactory.java:215)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.Annotate(SAMAnnotator.java:60)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.call(SAMAnnotator.java:160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
16:13:29.204 [pool-2-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - java.io.FileNotFoundException: /gpfs/ysm/project/neugebauer/da498/20210303coilRNAseq/2_pipeline/1_STAR (Is a directory)
htsjdk.samtools.util.RuntimeIOException: java.io.FileNotFoundException: /gpfs/ysm/project/neugebauer/da498/20210303coilRNAseq/2_pipeline/1_STAR (Is a directory)
	at htsjdk.samtools.FileInputResource$1.make(SamInputResource.java:198)
	at htsjdk.samtools.FileInputResource$1.make(SamInputResource.java:192)
	at htsjdk.samtools.util.Lazy.get(Lazy.java:24)
	at htsjdk.samtools.FileInputResource.asUnbufferedSeekableStream(SamInputResource.java:230)
	at htsjdk.samtools.FileInputResource.asUnbufferedInputStream(SamInputResource.java:235)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:282)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:145)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.Annotate(SAMAnnotator.java:59)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.call(SAMAnnotator.java:160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.FileNotFoundException: /gpfs/ysm/project/neugebauer/da498/20210303coilRNAseq/2_pipeline/1_STAR (Is a directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at htsjdk.samtools.seekablestream.SeekableFileStream.<init>(SeekableFileStream.java:47)
	at htsjdk.samtools.FileInputResource$1.make(SamInputResource.java:196)
	... 12 more

Thanks in advance for your help!

**Comment by cougarlj** [comment]
Dear DAE-113,

It seems that COMPSRA fails to open the bam file listed in the file. Could you run COMPSRA with "-in" and just take one bam file as an example? If it does work, there may be a potential bug for the "-inf" function.

Best Wishes,
  Jiang Li

**Comment by cougarlj** [comment]
Dear DAE-113,

It seems that COMPSRA fails to open the bam file listed in the file. Could you run COMPSRA with "-in" and just take one bam file as an example? If it does work, there may be a potential bug for the "-inf" function.

Best Wishes,
  Jiang Li

**Comment by DAE-113** [comment]
Hello,

Thanks for your help! I tried to run only one of the bam files and it continues giving me the same error in opening the file. The directory it is listing is not where I have the original STAR bam file, but instead seems to be a directory/file made by COMPSRA itself?

**Comment by sagarutturkar** [comment]
I am having the similar issue! I did use the find command to search for  "*_UnMapped.bam" files, but could not find any. Below are my commands:

```

java -jar COMPSRA.jar -ref hg38 -qc -ra AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC \
-rb 4 -rh 20 -rt 20 -rr 20 -rlh 8,17 \
-in /raw_data/BC-1_.fastq \
-out ./BC1/


java -jar COMPSRA.jar -ref hg38 -aln -mt star \
-in /3_COMPSRA/BC1/BC-1_S11_L001_R1_001/BC-1_S11_L001_R1_001_17to76_FitRead.fastq.gz \
/3_COMPSRA/BC1/BC-1_S11_L001_R1_001/BC-1_S11_L001_R1_001_17to76_FitRead/


java -jar COMPSRA.jar -ref hg38 -ann -ac 1,2,3,4,5,6 \
-in /3_COMPSRA/output/BC-1_S11_L001_R1_001_17to76_FitRead/BC-1_S11_L001_R1_001_17to76_FitRead_STAR_Aligned.out.bam \
-out /3_COMPSRA/output/BC-1_S11_L001_R1_001_17to76_FitRead/

```

**Comment by cougarlj** [comment]
Are there any bug messages?
