### ISSUE TITLE
Running Microbe Module

### ISSUE THREAD

**Issue by 84AP** [cougarlj/COMPSRA#25]
Hello,

I am trying to use the microbe module, however it does not work.

I noticed that the command:

"~ / COMPSRA $ java -jar COMPSRA.jar -tk -dr -ck blast_archaea"
"~ / COMPSRA $ java -jar COMPSRA.jar -tk -dr -ck blast_virus"
"~ / COMPSRA $ java -jar COMPSRA.jar -tk -dr -ck blast_bacteria"
"~ / COMPSRA $ java -jar COMPSRA.jar -tk -dr -ck blast_fungi"

does not download the pre-built full microbial databases.
 
Could you help me?
Thanks

**Comment by cougarlj** [comment]
Dear 84AP,

Thank you for using COMPSRA. Our server is not robust, so sometimes it's difficult to download the database. Maybe you can download (save as ... ) the resource by hand through https://regepi.bwh.harvard.edu/circurna/ . 

Thanks!

**Comment by amyhiteBISR** [comment]
I am having the same problem.  I'm assuming server connection problems. I was able to download the archaea manually, but get errors on virus, bacteria, and fungi.  Is there another source for these? 

Here is the error when downloading through COMPSRA:
13:09:40.756 [main] INFO  edu.harvard.channing.compass.utility.Download - Start to download the resource: https://regepi.bwh.harvard.edu/circurna/bundle_v1/db/nt/nt_fungi.fasta.gz
13:09:41.339 [main] INFO  edu.harvard.channing.compass.utility.Download - Fail to download the resource: https://regepi.bwh.harvard.edu/circurna/bundle_v1/db/nt/nt_fungi.fasta.gz
java.io.IOException: Server returned HTTP response code: 500 for URL: https://regepi.bwh.harvard.edu/circurna/bundle_v1/db/nt/nt_fungi.fasta.gz
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1484)
        at edu.harvard.channing.compass.utility.Download.download(Download.java:58)
        at edu.harvard.channing.compass.toolkit.DownloadResource.downloadResource(DownloadResource.java:211)
        at edu.harvard.channing.compass.toolkit.DownloadResource.runKit(DownloadResource.java:45)
        at edu.harvard.channing.compass.toolkit.ProduceTK.Dispatch(ProduceTK.java:41)
        at edu.harvard.channing.compass.core.COMPSRA.main(COMPSRA.java:54)
13:09:41.340 [main] INFO  edu.harvard.channing.compass.core.Produce - ToolKit module was completed.

**Comment by 84AP** [comment]
I am trying to download from  https://regepi.bwh.harvard.edu/circurna/  however
the site is protected and I cannot download the files.  Could you share a
compressed folder?


Il mer 10 nov 2021, 19:19 amyhiteBISR ***@***.***> ha scritto:

**Comment by cougarlj** [comment]
Dear amyhiteBISR,

Our server doesn't support file download well and we are trying to transfer
the resource to other servers. However, this still needs some time. It
should be finished early next year.

Best regards,
 Jiang Li

**Comment by cougarlj** [comment]
Dear 84AP,

Our server doesn't support file download well and we are trying to transfer
the resource to other servers. However, this still needs some time. It
should be finished early next year.

Best regards,
 Jiang Li
