### ISSUE TITLE
Fails to download the star

### ISSUE THREAD

**Issue by mars188** [cougarlj/COMPSRA#3]
Hi, 
I ran the following command to download the star: 
java -jar COMPSRA.jar -tk -dr -ck star
I get the following error: 

16:21:44.867 [main] INFO  edu.harvard.channing.compass.utility.Download - Start to download the resource: https://regepi.bwh.harvard.edu/circurna/bundle_v1/plug/star/STAR-2.5.3a.zip
16:21:46.237 [main] INFO  edu.harvard.channing.compass.utility.Download - Fail to download the resource: https://regepi.bwh.harvard.edu/circurna/bundle_v1/plug/star/STAR-2.5.3a.zip
java.io.FileNotFoundException: https://regepi.bwh.harvard.edu/circurna/bundle_v1/plug/star/STAR-2.5.3a.zip
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1909)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
        at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1484)
        at edu.harvard.channing.compass.utility.Download.download(Download.java:58)
        at edu.harvard.channing.compass.toolkit.DownloadResource.downloadResource(DownloadResource.java:211)
        at edu.harvard.channing.compass.toolkit.DownloadResource.runKit(DownloadResource.java:45)
        at edu.harvard.channing.compass.toolkit.ProduceTK.Dispatch(ProduceTK.java:41)
        at edu.harvard.channing.compass.core.COMPSRA.main(COMPSRA.java:54)
16:21:46.244 [main] INFO  edu.harvard.channing.compass.core.Produce - ToolKit module was completed.

Seems like the link to star is broken. Can someone help me to fix it, please? 

Thanks in advance!

**Comment by cougarlj** [comment]
Hi, mars188,

Thanks for the bug report. I have checked the resource and uploaded the file again. Please run the command from COMPSRA again. If any problem, please let me know. 

Best Wishes,
  Jiang Li

**Comment by mars188** [comment]
Hello Jiang, thank you for fixing the bug. It's working now! cheers!
