### ISSUE TITLE
issue in file merge

### ISSUE THREAD

**Issue by hafizmtalha** [cougarlj/COMPSRA#30]
I ran the whole pipeline and it was successful. but only now is that merge file has the same values for all columns and rows why is that ??? example written bellow

RNU6-1060P	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	
RNU1-67P	153.0	153.0	153.0	153.0	153.0	153.0	153.0	153.0	153.0	153.0	153.0	153.0	
RNU6-1072P	40.0	40.0	40.0	40.0	40.0	40.0	40.0	40.0	40.0	40.0	40.0	40.0	
RNU1-55P	3.0	3.0	3.0	3.0	3.0	3.0	3.0	3.0	3.0	3.0	3.0	3.0	
RNU6-492P	28.0	28.0	28.0	28.0	28.0	28.0	28.0	28.0	28.0	28.0	28.0	28.0	
RNVU1-6	7.0	7.0	7.0	7.0	7.0	7.0	7.0	7.0	7.0	7.0	7.0	7.0	
RNU4-52P	5.0	5.0	5.0	5.0	5.0	5.0	5.0	5.0	5.0	5.0	5.0	5.0	
RNVU1-1	726.0	726.0	726.0	726.0	726.0	726.0	726.0	726.0	726.0	726.0	726.0	726.0	
RNU6-1181P	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	
RNU2-48P	246.0	246.0	246.0	246.0	246.0	246.0	246.0	246.0	246.0	246.0	246.0	246.0	
RNU6-707P	185.0	185.0	185.0	185.0	185.0	185.0	185.0	185.0	185.0	185.0	185.0	185.0	
RNU2-36P	853.0	853.0	853.0	853.0	853.0	853.0	853.0	853.0	853.0	853.0	853.0	853.0	
RNU2-7P	168.0	168.0	168.0	168.0	168.0	168.0	168.0	168.0	168.0	168.0	168.0	168.0

**Comment by cougarlj** [comment]
Dear Hafiz,

Sorry to reply late. Welcome to use COMPSRA in your research. 

According to your description, it seems that COMPSRA only takes the first file as input and repeats it several times. To solve this problem, you can use the toolkit which has already been integrated into COMPSRA but not published. 

First, please run your samples one by one (you can submit jobs to the server together) and get the count file through the Annotation model. Then you can collect these files and put the full names into one file. At last, use the merge function in the toolkit to merge these counts. The command you can refer to is listed below. 

find /fullpath/example_out/ -name *_piRNA.txt | sort > /fullpath/example_out/your_sample.txt
java -jar COMPSRA.jar -tk -merge -id 0 -count 2 -inf /fullpath/example_out/your_sample.txt -out /fullpath/example_out/your_sample_piRNA_count.txt

Here, I take piRNA as an example. "find" is just the command in Linux OS in the first line. In the second line, "-tk" means using the toolkit and "-merge" means merging files. "-id 0" means the identifier is the first column and "-count 2" means the count is the third column. "-inf" means the input is a filelist  but not the count file itself. 

If you have any questions, please let me know.

Best Wishes,
  Jiang Li

**Comment by hafizmtalha** [comment]
Thankyou for the help. I tried this but it gives me the following error

java -jar COMPSRA.jar -tk -merge -id 0 -count 2 -inf all-samples.txt -out merge_miRNA.txt

+++++++++++++++++++++++++++++++
+            COMPSRA          +
+     (V1.0.2 2020-07-03)     +
+  rejia@channing.harvard.edu +
+++++++++++++++++++++++++++++++


Working Directory: /media/pc/Bay2/Softwares/COMPSRA_V1.0.3
Bundle Directory: /media/pc/Bay2/Softwares/COMPSRA_V1.0.3/bundle_v1
Configuration Directory: /media/pc/Bay2/Softwares/COMPSRA_V1.0.3/bundle_v1/configuration
Plug Directory: /media/pc/Bay2/Softwares/COMPSRA_V1.0.3/bundle_v1/plug
N_CPU: 80

Configuration Info: The endogenous database configuration has been set!
Configuration Info: 37 databases are set!
00:04:14.988 [main] INFO  edu.harvard.channing.compass.core.Configuration - The Configuration was completed!

00:04:15.001 [main] ERROR edu.harvard.channing.compass.toolkit.ProduceTK - No ToolKit was set!

**Comment by cougarlj** [comment]
Dear Hafiz,

Please use the COMPSRA V1.0.3, which you can download from GitHub. Maybe
the pre-built database should also be updated.

Best Wishes,
Jiang Li

**Comment by hafizmtalha** [comment]
I downloaded version 1.0.3, but the jar file it contains has version 1.0.2. 
I tried downloading version 1.0.2 as well and it has the file with version 1.0.1
Kindly check

**Comment by cougarlj** [comment]
Dear Hafiz,

I'm sorry for the mistake. You can download COMPSRA from GitHub (
https://github.com/cougarlj/COMPSRA/blob/master/COMPSRA_V1.0.3.zip), which
should be the latest version. And the pre-built databases could be
downloaded from GitHub too by hand (
https://github.com/cougarlj/COMPSRA/tree/master/bundle_v1/prebuilt_db).

Best Wishes,
  Jiang Li

**Comment by hafizmtalha** [comment]
I have downloaded this again.. but when I run the jar file it's again shows the version 1.0.2. 
kindly check..

**Comment by cougarlj** [comment]
Dear Hafiz,

Oh, I may forget to change the output of version info. It should contain a
toolkit plug inside.

Best Wishes,
  Jiang Li

**Comment by hafizmtalha** [comment]
Still the same error. No toolkit was set
my comand:
java -jar COMPSRA.jar -tk -merge -id 0 -count 2 -inf mirRNA-samples.txt -out merge_miRNA.txt

**Comment by cougarlj** [comment]
Dear Hafiz,

I'm sorry for the inconvenience. Please change "-merge" to "-Merge". I
forget that I have changed the lower case to upper case.

Best regards,
  Jiang Li

**Comment by hafizmtalha** [comment]
This one worked but sadly another error.. looks like this one is related to input files..

10:19:03.493 [main] ERROR java.lang.Class - java.lang.NumberFormatException: For input string: "-"
10:19:03.493 [main] ERROR java.lang.Class - java.lang.NumberFormatException: For input string: "-"
10:19:03.494 [main] ERROR java.lang.Class - java.lang.NumberFormatException: For input string: "-"
10:19:03.494 [main] ERROR java.lang.Class - java.lang.NumberFormatException: For input string: "-"
10:19:03.494 [main] ERROR java.lang.Class - java.lang.NumberFormatException: For input string: "-"
Exception in thread "main" java.lang.NullPointerException
at edu.harvard.channing.compass.core.Factory.getWriter(Factory.java:153)
at edu.harvard.channing.compass.toolkit.Merge.outputResult(Merge.java:126)
at edu.harvard.channing.compass.toolkit.Merge.runKit(Merge.java:80)
at edu.harvard.channing.compass.toolkit.ProduceTK.Dispatch(ProduceTK.java:41)
at edu.harvard.channing.compass.core.COMPSRA.main(COMPSRA.java:54)

my input file headers are
SRR1759258_miRNA.txt
SRR1759259_miRNA.txt
SRR1759260_miRNA.txt
SRR1759261_miRNA.txt
SRR1759262_miRNA.txt
SRR1759263_miRNA.txt
SRR1759264_miRNA.txt
SRR1759265_miRNA.txt

count file header looks like this
DB      Name    ID      Count
miRBase hsa-miR-4446-3p -       33
miRBase hsa-mir-4797    -       4
miRBase hsa-mir-4790    -       1
miRBase hsa-miR-99b-3p  -       314
miRBase hsa-miR-6868-3p -       7
miRBase hsa-miR-19b-1-5p        -       4
miRBase hsa-miR-375     -       424
miRBase hsa-miR-767-3p  -       1
miRBase hsa-miR-548a-3p -       3
miRBase hsa-mir-4798    -       1
miRBase hsa-miR-7151-3p -       6
miRBase hsa-mir-1270    -       1
miRBase hsa-mir-1276    -       1
miRBase hsa-mir-4780    -       11
miRBase hsa-mir-1277    -       34
miRBase hsa-miR-767-5p  -       142
miRBase hsa-miR-939-3p  -       1
miRBase hsa-miR-6754-3p -       3
miRBase hsa-miR-2277-3p -       10
miRBase hsa-miR-493-3p  -       10
miRBase hsa-miR-181a-2-3p       -       1779
miRBase hsa-mir-6513    -       2
miRBase hsa-miR-101-5p  -       628

**Comment by cougarlj** [comment]
Der Hafiz,
You can try:
java -jar COMPSRA.jar -tk -Merge -id 1 -count 3 -inf mirRNA-samples.txt
-out merge_miRNA.txt

This function is very independent. For any file with columns, you can use
this to merge data with the right "-id" and "-count" parameters.

Best Wishes,
  Jiang Li

**Comment by hafizmtalha** [comment]
thanks for you kind help..
later I realized this and I changed the parameters as mentioned in your reply (-id 1 -count 3).. but the error changed to this :D

17:25:24.601 [main] INFO  java.lang.Class - The file SRR1759264_miRNA.txt was extracted.
17:25:24.601 [main] INFO  java.lang.Class - The file SRR1759265_miRNA.txt was extracted.
17:25:24.601 [main] INFO  java.lang.Class - The file SRR1759266_miRNA.txt was extracted.
17:25:24.602 [main] INFO  java.lang.Class - The file SRR1759267_miRNA.txt was extracted.
17:25:24.602 [main] INFO  java.lang.Class - The file SRR1759268_miRNA.txt was extracted.
17:25:24.602 [main] INFO  java.lang.Class - The file SRR1759269_miRNA.txt was extracted.
17:25:24.602 [main] INFO  java.lang.Class - The file SRR1759270_miRNA.txt was extracted.
17:25:24.602 [main] INFO  java.lang.Class - The file SRR1759271_miRNA.txt was extracted.
17:25:24.603 [main] INFO  java.lang.Class - The file SRR1759272_miRNA.txt was extracted.
17:25:24.603 [main] INFO  java.lang.Class - The file SRR1759273_miRNA.txt was extracted.
17:25:24.603 [main] INFO  java.lang.Class - The file SRR1759274_miRNA.txt was extracted.
17:25:24.604 [main] INFO  java.lang.Class - The file SRR1759275_miRNA.txt was extracted.
Exception in thread "main" java.lang.NullPointerException
at edu.harvard.channing.compass.core.Factory.getWriter(Factory.java:153)
at edu.harvard.channing.compass.toolkit.Merge.outputResult(Merge.java:126)
at edu.harvard.channing.compass.toolkit.Merge.runKit(Merge.java:80)
at edu.harvard.channing.compass.toolkit.ProduceTK.Dispatch(ProduceTK.java:41)
at edu.harvard.channing.compass.core.COMPSRA.main(COMPSRA.java:54)

**Comment by cougarlj** [comment]
Dear hafizmtalha,

Pleas use the fullname of the output file, such as -out /media/pc/Bay2/Softwares/COMPSRA_V1.0.3/output/merge_miRNA.txt

Best Wishes
  Jiang Li

**Comment by hafizmtalha** [comment]
Thanks for all the help.. it worked

**Comment by cougarlj** [comment]
Good! Thank you for using COMPSRA.
