### ISSUE TITLE
Fail to find the prebuilt database obj file! (But it is there!)

### ISSUE THREAD

**Issue by raquelgarza** [cougarlj/COMPSRA#34]
Hi! 

I followed the instructions to download all resources as the example you provided in the README (using mm10 instead of hg38):

`~/COMPSRA$ java -jar COMPSRA.jar -tk -dr -ck miRNA_hg38,piRNA_hg38,tRNA_hg38,snoRNA_hg38,snRNA_hg38,circRNA_hg38`

I got everything I need I think (see tree.txt for the listed content of bundle_v1). However, I get this error message when running the pipeline:

```
17:09:59.746 [pool-3-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - edu.harvard.channing.compass.entity.DBTree; local class incompatible: stream classdesc serialVersionUID = 1386352989058994328, local class serialVersionUID = 556476181312992002
17:09:59.747 [pool-3-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - Fail to find the prebuilt database obj file!
17:09:59.747 [pool-3-thread-1] WARN  edu.harvard.channing.compass.db.DB_miRBase - The prebuilt database file /Users/Documents/Projects/src/bundle_v1/prebuilt_db/miRBase_mm10.obj doesn't exist!
17:09:59.747 [pool-3-thread-1] INFO  edu.harvard.channing.compass.db.DB_miRBase - Try to build the database from local files /Users/Documents/Projects/src/bundle_v1/db/miRBase/miRBase_mm10.gff3 !
17:09:59.747 [pool-3-thread-1] INFO  edu.harvard.channing.compass.utility.ReadFile - Read File Error: Fail to read file: /Users/Documents/Projects/src/bundle_v1/db/miRBase/miRBase_mm10.gff3.
17:09:59.748 [pool-3-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - null
java.lang.NullPointerException
	at edu.harvard.channing.compass.utility.ReadFile.readGFF3(ReadFile.java:384)
	at edu.harvard.channing.compass.db.DB_miRBase.getForest(DB_miRBase.java:85)
	at edu.harvard.channing.compass.core.ann.IPTR_miRNA.buildForest(IPTR_miRNA.java:51)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.Annotate(SAMAnnotator.java:78)
	at edu.harvard.channing.compass.core.ann.SAMAnnotator.call(SAMAnnotator.java:159)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17:09:59.749 [main] ERROR edu.harvard.channing.compass.core.ann.Annotation - java.lang.NullPointerException
17:09:59.749 [main] INFO  edu.harvard.channing.compass.core.Produce - Error: Annotation module fails!
```

If I understand correctly, miRBase_mm10.gff3 is produced from the miRBase_mm10.obj, and for some reason this object can't be found (although the bundle_v1 directory is in the same directory I'm running COMPSRA at, and the file is looking it for **does** exist: /Users/Documents/Projects/src/bundle_v1/prebuilt_db/miRBase_mm10.obj).

Any ideas what could be going wrong?

Thanks,

[tree.txt](https://github.com/cougarlj/COMPSRA/files/8312340/tree.txt)

**Comment by cougarlj** [comment]
Dear aquelgarza,

According to the error message, it seems that the version of COMPSRA doesn't match the bundle, because of the serialVersionUID. When this happen, COMPSRA will try to download the target files from UCSC/miRBase/some other databases and builds them into pre-built databases. So did you use the latest version of COMPSRA? 

Best Wishes,
  Jiang Li

**Comment by SoManyPepople** [comment]
> 

+++++++++++++++++++++++++++++++
+   Module  --->  Annotation  +
+++++++++++++++++++++++++++++++

DEBUG   2022-03-30 09:54:48     BlockCompressedOutputStream     Using deflater: Deflater
09:54:48.270 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - Not in GZIP format
09:54:48.270 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - Fail to find the prebuilt database obj file!
09:54:48.270 [pool-2-thread-1] WARN  edu.harvard.channing.compass.db.DB_miRBase - The prebuilt database file /public/home/huangp/software/COMPSRA/bundle_v1/prebuilt_db/miRBase_mm10.obj doesn't exist!
09:54:48.271 [pool-2-thread-1] INFO  edu.harvard.channing.compass.db.DB_miRBase - Try to build the database from local files /public/home/huangp/software/COMPSRA/bundle_v1/db/miRBase/miRBase_mm10.gff3 !
09:54:48.271 [pool-2-thread-1] INFO  edu.harvard.channing.compass.core.Factory - Read File Error: Fail to read file: miRBase_v21
09:54:48.271 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - null
09:54:48.272 [pool-2-thread-1] INFO  edu.harvard.channing.compass.utility.ReadFile - Read File Error: Fail to read file: /public/home/huangp/software/COMPSRA/bundle_v1/db/miRBase/miRBase_mm10.gff3.
09:54:48.272 [pool-2-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - null
java.lang.NullPointerException
        at edu.harvard.channing.compass.utility.ReadFile.readGFF3(ReadFile.java:384)
        at edu.harvard.channing.compass.db.DB_miRBase.getForest(DB_miRBase.java:102)
        at edu.harvard.channing.compass.core.ann.IPTR_miRNA.buildForest(IPTR_miRNA.java:51)
        at edu.harvard.channing.compass.core.ann.SAMAnnotator.Annotate(SAMAnnotator.java:79)
        at edu.harvard.channing.compass.core.ann.SAMAnnotator.call(SAMAnnotator.java:160)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
09:54:48.273 [main] ERROR edu.harvard.channing.compass.core.ann.Annotation - java.lang.NullPointerException
09:54:48.274 [main] INFO  edu.harvard.channing.compass.core.Produce - Error: Annotation module fails!

Hi, Li Jiang,
I just got the same problem. I downloaded the newest version of COMPSRA and obj files for mm10 via the link you provided in your reply to another issue. Do you have any idea about this error?

**Comment by raquelgarza** [comment]
Hi,

Thank you for your answer. But yes, I used the latest version of COMPSRA.

**Comment by cougarlj** [comment]
Dear SoManyPeople,

Another method to solve this problem is to let COMPSRA build the pre-built database by itself. Please directly download the file mm10.gff3 from miRBase and rename and put it in /public/home/huangp/software/COMPSRA/bundle_v1/db/miRBase/miRBase_mm10.gff3

Best Wishes,
  Jiang Li

**Comment by cougarlj** [comment]
> Hi,
> 
> Thank you for your answer. But yes, I used the latest version of COMPSRA.

Dear raquelgarza,

Please download these files from GitHub manually and try it again. 

Best Wishes,
  Jiang Li
