### ISSUE TITLE
Annotation module error

### ISSUE THREAD

**Issue by Ben7124** [cougarlj/COMPSRA#45]
Hello,
I used the example command:

 java -jar COMPSRA.jar -ref hg38 -ann -ac 1,2,3,4,5,6 -in ./example_out/sample01/sample01_17to50_FitRead_STAR_Aligned.out.bam -out ./example_out/sample01/sample01_17to50_FitRead_STAR_Aligned

But I get the below error: Fail to find the prebuilt database obj file! , but I even redownloaded the obj files and they are there. Can you please help me to fix this issue? Thanks!

DEBUG   2022-07-14 21:06:32     BlockCompressedOutputStream     Using deflater: Deflater
21:06:32.939 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - edu.harvard.channing.compass.entity.DBTree; local class incompatible: stream classdesc serialVersionUID = 556476181312992002, local class serialVersionUID = 1386352989058994328
21:06:32.940 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - Fail to find the prebuilt database obj file!
21:06:32.940 [pool-2-thread-1] WARN  edu.harvard.channing.compass.db.DB_miRBase - The prebuilt database file /home/ubu/COMPSRA/bundle_v1/prebuilt_db/miRBase_hg38.obj doesn't exist!
21:06:32.940 [pool-2-thread-1] INFO  edu.harvard.channing.compass.db.DB_miRBase - Try to build the database from local files /home/ubu/COMPSRA/bundle_v1/db/miRBase/miRBase_hg38.gff3 !
21:06:32.941 [pool-2-thread-1] INFO  edu.harvard.channing.compass.core.Factory - Read File Error: Fail to read file: miRBase_v21
21:06:32.941 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - null
21:06:32.941 [pool-2-thread-1] INFO  edu.harvard.channing.compass.utility.ReadFile - Read File Error: Fail to read file: /home/ubu/COMPSRA/bundle_v1/db/miRBase/miRBase_hg38.gff3.
21:06:32.941 [pool-2-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - null
java.lang.NullPointerException
        at edu.harvard.channing.compass.utility.ReadFile.readGFF3(ReadFile.java:384)
        at edu.harvard.channing.compass.db.DB_miRBase.getForest(DB_miRBase.java:102)
        at edu.harvard.channing.compass.core.ann.IPTR_miRNA.buildForest(IPTR_miRNA.java:51)
        at edu.harvard.channing.compass.core.ann.SAMAnnotator.Annotate(SAMAnnotator.java:79)
        at edu.harvard.channing.compass.core.ann.SAMAnnotator.call(SAMAnnotator.java:160)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
21:06:32.942 [main] ERROR edu.harvard.channing.compass.core.ann.Annotation - java.lang.NullPointerException
21:06:32.942 [main] INFO  edu.harvard.channing.compass.core.Produce - Error: Annotation module fails!

**Comment by Ben7124** [comment]
Ok thank you I figured out the issue. When you unzip the zip file, unzip into a separate directory and copy it into the main COMPSRA directory. I skipped the downloading of the databases via the command line and just used the ones in the bundle_v1 directory. It looks like it's working now.
