### ISSUE TITLE
Fail to find the prebuilt database obj file

### ISSUE THREAD

**Issue by kengjunglee** [cougarlj/COMPSRA#51]
Hello,

I used the latest COMPSRA V1.0.3 version and I also confirm that I have miRBase_hg38.obj in the target file. 
But I still get this error. Could you kindly let me know how to solve it? 

Thanks

+++++++++++++++++++++++++++++++
+   Module  --->  Annotation  +
+++++++++++++++++++++++++++++++

DEBUG   2023-02-20 14:41:19     BlockCompressedOutputStream     Using deflater: Deflater
14:41:19.302 [pool-4-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - Not in GZIP format
14:41:19.303 [pool-4-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - Fail to find the prebuilt database obj file!
14:41:19.303 [pool-4-thread-1] WARN  edu.harvard.channing.compass.db.DB_miRBase - The prebuilt database file /home/ubuntu/COMPSRA/bundle_v1/prebuilt_db/miRBase_hg38.obj doesn't exist!
14:41:19.303 [pool-4-thread-1] INFO  edu.harvard.channing.compass.db.DB_miRBase - Try to build the database from local files /home/ubuntu/COMPSRA/bundle_v1/db/miRBase/miRBase_hg38.gff3 !
14:41:19.303 [pool-4-thread-1] INFO  edu.harvard.channing.compass.core.Factory - Read File Error: Fail to read file: miRBase_v21
14:41:19.303 [pool-4-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - null
14:41:19.304 [pool-4-thread-1] INFO  edu.harvard.channing.compass.utility.ReadFile - Read File Error: Fail to read file: /home/ubuntu/COMPSRA/bundle_v1/db/miRBase/miRBase_hg38.gff3.
14:41:19.304 [pool-4-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - null
java.lang.NullPointerException
        at edu.harvard.channing.compass.utility.ReadFile.readGFF3(ReadFile.java:384)
        at edu.harvard.channing.compass.db.DB_miRBase.getForest(DB_miRBase.java:102)
        at edu.harvard.channing.compass.core.ann.IPTR_miRNA.buildForest(IPTR_miRNA.java:51)
        at edu.harvard.channing.compass.core.ann.SAMAnnotator.Annotate(SAMAnnotator.java:79)
        at edu.harvard.channing.compass.core.ann.SAMAnnotator.call(SAMAnnotator.java:160)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
14:41:19.305 [main] ERROR edu.harvard.channing.compass.core.ann.Annotation - java.lang.NullPointerException
14:41:19.305 [main] INFO  edu.harvard.channing.compass.core.Produce - Error: Annotation module fails!

**Comment by cougarlj** [comment]
Dear kengjunglee,

Sorry for the late reply. It seems that COMPSRA couldn't find the obj file.
The reason may be that the obj file was damaged inside. You can download
the obj file again from GitHub. Another way is to download the
miRBase_hg38.gff3 file from miRBase database and put this file
in  /home/ubuntu/COMPSRA/bundle_v1/db/miRBase/ . In this situation, COMPSRA
will build the obj file automatically. If you have any questions, please
let me know.

Best regards,
  Jiang Li
