### ISSUE TITLE
Downloading files from https://regepi.bwh.harvard.edu/circurna/bundle_v1/db/nt

### ISSUE THREAD

**Issue by brianherb** [cougarlj/COMPSRA#57]
Hi, 

Thank you for this tool. I get errors when trying to download files from https://regepi.bwh.harvard.edu/circurna/bundle_v1/db/nt - for example: 

java -jar COMPSRA.jar -tk -dr -ck blast_bacteria

+++++++++++++++++++++++++++++++
+            COMPSRA          +
+     (V1.0.2 2020-07-03)     +
+  rejia@channing.harvard.edu +
+++++++++++++++++++++++++++++++

Working Directory: /autofs/burnsfs/projects-t3/idea/amentlab_software/COMPSRA
Bundle Directory: /autofs/burnsfs/projects-t3/idea/amentlab_software/COMPSRA/bundle_v1
Configuration Directory: /autofs/burnsfs/projects-t3/idea/amentlab_software/COMPSRA/bundle_v1/configuration                                                                                              
Plug Directory: /autofs/burnsfs/projects-t3/idea/amentlab_software/COMPSRA/bundle_v1/plug
N_CPU: 48

Configuration Info: The endogenous database configuration has been set!
Configuration Info: 37 databases are set!
09:49:32.259 [main] INFO  edu.harvard.channing.compass.core.Configuration - The Configuration was completed!                                                                                             

+++++++++++++++++++++++++++++++
+      COMPASS ---> ToolKit   +
+++++++++++++++++++++++++++++++

09:49:32.267 [main] INFO  edu.harvard.channing.compass.utility.Download - Start to download the resource: https://regepi.bwh.harvard.edu/circurna/bundle_v1/db/nt/nt_bacteria.fasta.gz                   
09:49:33.093 [main] INFO  edu.harvard.channing.compass.utility.Download - Finish to download the resource: https://regepi.bwh.harvard.edu/circurna/bundle_v1/db/nt/nt_bacteria.fasta.gz                  
**09:49:33.105 [main] ERROR edu.harvard.channing.compass.core.Factory - Not in GZIP format**
Exception in thread "main" java.lang.NullPointerException
        at edu.harvard.channing.compass.utility.DeCompress.UnGZipFile(DeCompress.java:54)
        at edu.harvard.channing.compass.utility.Download.download(Download.java:66)
        at edu.harvard.channing.compass.toolkit.DownloadResource.downloadResource(DownloadResource.java:221)                                                                                             
        at edu.harvard.channing.compass.toolkit.DownloadResource.runKit(DownloadResource.java:45)
        at edu.harvard.channing.compass.toolkit.ProduceTK.Dispatch(ProduceTK.java:41)
        at edu.harvard.channing.compass.core.COMPSRA.main(COMPSRA.java:54)

**Comment by cougarlj** [comment]
Dear Brain,

Currently, our server is not open for downloading resource files. I'm
afraid that the microbiome module is not available now. Or you can download
nt database directly from UCSC and extract bacterial sequences by yourself.
I'm sorry for the inconvenience. We will try to move the resource to
another server in COMPSRA2 this year.

Best regards,
  Jiang Li
